---
-
  hosts: ubuntu
  
  tasks:
    - name: Instalar GNUPG
      package:
        name: gnupg
        state: latest

    - name: Adicionar a chave APT
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present
        
    - name: Adicionar o repositório
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome
        update_cache: True

    - name: Instalar Pacotes Chrome, NodeJS, NPM, Curl, VIM, Wget, GIT, Unrar, Unzip, Xrdp, Dconf-editor, Alacarte, Snapd
      package:
        name: "{{ item }}"
        state: latest
        update_cache: True
      with_items: ['google-chrome-stable', 
                   'nodejs', 
                   'npm', 
                   'curl', 
                   'vim', 
                   'wget', 
                   'git', 
                   'unrar', 
                   'unzip', 
                   'xrdp', 
                   'dconf-editor', 
                   'alacarte', 
                   'snapd']

    - name: Instalar LightDM
      package:
        name: 'lightdm'

    - name: Desabilitar gdm3
      service:
        name: gdm3
        state: stopped
        enabled: no

    - name: Instalar XFCE4
      apt:
        name: [ 'xserver-xorg', 'xfonts-base', 'xubuntu-desktop' ]

    - name: Iniciar SNAP
      service:
        name: snapd
        state: started

    - name: Ativar SNAP
      service:
        name: snapd
        enabled: yes

    - name: Instalar ark
      snap:
        name: ark
        classic: no

    - name: Instalar luminati-io
      npm:
        name: "@luminati-io/luminati-proxy"
        global: yes
        state: latest

    - name: Instalar pm2
      npm:
        name: pm2
        global: yes
        state: latest

    - name: Criação do Usuário
      user:
        name: teste
        password: "{{ '1234' | password_hash('sha512') }}"
        state: present
        shell: "/bin/bash"
        groups: sudo
        append: yes

    - name: Ajuste de criptografia (XRDP)
      replace:
        path: /etc/xrdp/xrdp.ini
        regexp:  '^crypt_level=high$'
        replace: 'crypt_level=low'

    - name: Ajuste de BPP (XRDP)
      replace:
        path: /etc/xrdp/xrdp.ini
        regexp:  '^max_bpp=32$'
        replace: 'max_bpp=128'

    - name: Ajuste startwm.sh 01 (XRDP)
      replace:
        path: /etc/xrdp/startwm.sh
        regexp:  '^test -x'
        replace: '#test -x'

    - name: Ajuste startwm.sh 02 (XRDP)
      replace:
        path: /etc/xrdp/startwm.sh
        regexp:  '^exec'
        replace: '#exec'
        
    - name: Inserir startxfce ao fim do arquivo /etc/xrdp/startwm.sh
      lineinfile:
        path: /etc/xrdp/startwm.sh
        line: startxfce4

    - name: Configurar Polkit 
      copy:
        src: files/polkit
        dest: /etc/polkit-1/localauthority.conf.d/02-allow-colord.conf

    - name: Configurar serviço Luminati 
      copy:
        src: files/luminati.service
        dest: /etc/systemd/system/luminati.service

    - name: Habilitando o Ambiente Gráfico
      command: systemctl set-default graphical.target

    - name: Daemon Reload
      systemd:
        daemon_reload: yes

    - name: Desativar AppArmor
      service:
        name: apparmor
        state: stopped
        enabled: no

    - name: Desativar UFW
      service:
        name: ufw
        state: stopped
        enabled: no

    - name: Ativar XRDP
      service:
        name: xrdp
        state: started
        enabled: yes

    - name: Ativar Luminati
      service:
        name: luminati
        state: started
        enabled: yes
...
