---
-
  hosts: ubuntu

  vars:
    polkit: |
      polkit.addRule(function(action, subject) {
       if ((action.id == "org.freedesktop.color-manager.create-device" ||
       action.id == "org.freedesktop.color-manager.create-profile" ||
       action.id == "org.freedesktop.color-manager.delete-device" ||
       action.id == "org.freedesktop.color-manager.delete-profile" ||
       action.id == "org.freedesktop.color-manager.modify-device" ||
       action.id == "org.freedesktop.color-manager.modify-profile") &&
       subject.isInGroup("{users}")) {
       return polkit.Result.YES;
       }
       });

    luminati: |
      [Unit]
      Description="Serviço Luminati Proxy"
      After=network.target
      Requires=network.target
      [Service]
      User=teste
      ExecStart=luminati-proxy --daemon
      StandardError=syslog
      SyslogIdentifier=LUMINATI_PROXY
      [Install]
      WantedBy=graphical.target
  
  tasks:
    - name: Instalar GNUPG
      package:
        name: gnupg
        state: latest

    - name: Adicionar a chave APT
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present
        
    - name: Adicionar o repositório
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome
        update_cache: True

    - name: Instalar Pacotes Chrome, NodeJS, NPM, Curl, VIM, Wget, GIT, Unrar, Unzip, Xrdp, Dconf-editor, Alacarte, Snapd
      package:
        name: ['google-chrome-stable', 'nodejs', 'npm', 'curl', 'vim', 'wget', 'git', 'unrar', 'unzip', 'xrdp', 'dconf-editor', 'alacarte', 'snapd']
        state: latest
        update_cache: True

    - name: Instalar XFCE4
      apt:
        name: [ 'xserver-xorg', 'xfonts-base', 'xubuntu-desktop', 'lightdm' ]

    - name: Iniciar SNAP
      service:
        name: snapd
        state: started

    - name: Ativar SNAP
      service:
        name: snapd
        enabled: yes

    - name: Instalar ark
      snap:
        name: ark
        classic: no

    - name: Instalar luminati-io
      npm:
        name: "@luminati-io/luminati-proxy"
        global: yes
        state: latest

    - name: Instalar pm2
      npm:
        name: pm2
        global: yes
        state: latest

    - name: Criação do Usuário
      user:
        name: teste
        password: "{{ '1234' | password_hash('sha512') }}"
        state: present
        shell: "/bin/bash"
        groups: sudo
        append: yes

    - name: Configuração XRDP
      command: "{{ item }}"
      with_items:
        - sed -i 's/crypt_level=high/crypt_level=low/g' /etc/xrdp/xrdp.ini
        - sed -i 's/max_bpp=32/max_bpp=128/g' /etc/xrdp/xrdp.ini
        - sed -i 's/test -x/#test -x/g' /etc/xrdp/startwm.sh
        - sed -i 's/exec/#exec/g' /etc/xrdp/startwm.sh
        
    - name: Inserir startxfce ao fim do arquivo /etc/xrdp/startwm.sh
      lineinfile:
        path: /etc/xrdp/startwm.sh
        line: startxfce4

    - copy:
        dest: /etc/polkit-1/localauthority.conf.d/02-allow-colord.conf
        content: "{{ polkit }}"

    - copy:
        dest: /etc/systemd/system/luminati.service
        content: "{{ luminati }}"

    - name: Habilitando o Ambiente Gráfico
      command: systemctl set-default graphical.target

    - name: Daemon Reload
      command: systemctl daemon-reload

    - name: Desativar AppArmor
      service:
        name: apparmor
        state: stopped
        enabled: no

    - name: Desativar UFW
      service:
        name: ufw
        state: stopped
        enabled: no

    - name: Ativar Serviços
      service:
        name: xrdp
        state: started
        enabled: yes

    - name: Ativar Serviços
      service:
        name: luminati
        state: started
        enabled: yes

...
